# Generated by Django 5.1.4 on 2024-12-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_socialmedialink"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialink",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="platform",
            field=models.CharField(max_length=100),
        ),
    ]
