# Generated by Django 5.1.4 on 2024-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_linkclick"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "Regular User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
