# Generated by Django 5.1.2 on 2024-12-17 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_role_notification_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmedialink",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Social Media Link",
                "verbose_name_plural": "Social Media Links",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="users.Follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="click_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Facebook", "Facebook"),
                    ("Twitter", "Twitter"),
                    ("Instagram", "Instagram"),
                    ("LinkedIn", "LinkedIn"),
                    ("YouTube", "YouTube"),
                    ("GitHub", "GitHub"),
                    ("Website", "Personal Website"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url",
            field=models.URLField(
                help_text="Enter the full URL (e.g., https://example.com)"
            ),
        ),
    ]
